/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Address {
  city: string;
  company?: string;
  country?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  phone?: string;
  postal?: string;
  region?: string;
  streets: string[];
  [k: string]: unknown;
}
export interface MapStringObject {
  [k: string]: unknown;
}
