/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Method = "CASH" | "PO" | "CREDIT_CARD" | "ON_ACCOUNT";
export type Provider = "FedEx" | "UPS" | "USPS" | "Other";
export type Status = "CREATED";

export interface All {
  address?: Address;
  customer?: Customer;
  order?: Order;
  product?: Product;
  shipment?: Shipment;
  [k: string]: unknown;
}
export interface Address {
  city: string;
  company?: string;
  country?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  phone?: string;
  postal?: string;
  region?: string;
  streets: string[];
  [k: string]: unknown;
}
export interface MapStringObject {
  [k: string]: unknown;
}
export interface Customer {
  addresses?: Address[];
  email?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  [k: string]: unknown;
}
export interface Order {
  billingAddress: Address;
  comments?: string;
  currencyCode?: string;
  customerIdentifiers?: MapStringObject;
  discounts?: Discount[];
  email?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  /**
   * @minItems 1
   */
  lineItems: [LineItem, ...LineItem[]];
  orderDate?: string;
  /**
   * Globally unique orderNumber.  Usually a combination of sales channel and order number
   */
  orderNumber: string;
  payments?: Payment[];
  salesChannel: string;
  shippingAddress?: Address;
  shippingAmount: number;
  shippingInfo?: ShippingInfo;
  status?: Status;
  subtotal: number;
  taxAmount: number;
  total: number;
  [k: string]: unknown;
}
export interface Discount {
  amount?: number;
  code?: string;
  description?: string;
  identifiers?: MapStringObject;
  [k: string]: unknown;
}
export interface LineItem {
  children?: LineItem[];
  discountAmount?: number;
  identifiers?: MapStringObject;
  imageUrls?: string[];
  name: string;
  productIdentifiers?: MapStringObject;
  quantity: number;
  sku: string;
  subtotal: number;
  taxAmount: number;
  total: number;
  weightInPounds: number;
  [k: string]: unknown;
}
export interface Payment {
  amount?: number;
  billToName?: string;
  identifiers?: MapStringObject;
  method: Method;
  paymentDate?: string;
  poNumber?: string;
  status?: string;
  [k: string]: unknown;
}
export interface ShippingInfo {
  accountNumber?: string;
  accountType?: string;
  isBlindShipping: boolean;
  method?: string;
  provider: Provider;
  weightInPounds?: number;
  [k: string]: unknown;
}
export interface Product {
  badges?: ProductBadge[];
  brand: string;
  browsable: boolean;
  content?: ProductContent;
  createdAt?: string;
  customization?: ProductCustomization;
  identifiers?: MapStringObject;
  media?: ProductMedia[];
  name: string;
  primaryCategory?: CategoryReference;
  purchaseOptions?: PurchaseOptions;
  searchable: boolean;
  sku: string;
  status?: string;
  taxonomy: Taxonomy;
  upc?: string;
  updatedAt?: string;
  url: string;
  [k: string]: unknown;
}
export interface ProductBadge {
  id?: number;
  imageUrl?: string;
  label?: string;
  [k: string]: unknown;
}
export interface ProductContent {
  longDescription?: string;
  metaDescription?: string;
  metaKeywords?: string;
  metaTitle?: string;
  seoDescription?: string;
  shortDescription?: string;
  [k: string]: unknown;
}
export interface ProductCustomization {
  designRequired: boolean;
  prebuiltConfigurationId?: string;
  prebuiltCustomizable: boolean;
  prebuiltDesign: boolean;
  [k: string]: unknown;
}
export interface ProductMedia {
  altText?: string;
  mediaType: string;
  tags?: string[];
  url: string;
  [k: string]: unknown;
}
export interface CategoryReference {
  id: number;
  label: string;
  url: string;
  [k: string]: unknown;
}
export interface PurchaseOptions {
  allowsSample: boolean;
  availability: string;
  basePrice: number;
  customizable: boolean;
  customizeLeadTimeDayRange?: string;
  discountReason?: string;
  inStock: boolean;
  leadTime?: string;
  minCustomizationQty?: number;
  minSaleQty: number;
  onSale?: boolean;
  plainLeadTimeDayRange?: string;
  price: number;
  quantityStepIncrements?: QuantityStepIncrement[];
  salePrice?: number;
  stockQty: number;
  suggestedQuantityDisplays?: number[];
  tierPrices?: TierPrice[];
  toBeDiscontinued: boolean;
  [k: string]: unknown;
}
export interface QuantityStepIncrement {
  requiredStepIncrement: number;
  startingAtQty: number;
  [k: string]: unknown;
}
export interface TierPrice {
  price: number;
  startingAtQty: number;
  [k: string]: unknown;
}
export interface Taxonomy {
  additionalProperties?: MapStringObject;
  master: string;
  primary: string;
  sub: string;
  [k: string]: unknown;
}
export interface Shipment {
  carrier?: string;
  comments?: string;
  currencyCode?: string;
  estimatedDeliveryDate?: string;
  identifiers?: MapStringObject;
  lineItems?: LineItem[];
  orderIdentifiers?: MapStringObject;
  /**
   * Globally unique orderNumber.  Usually a combination of sales channel and order number
   */
  orderNumber: string;
  shipmentDate: string;
  trackingNumber?: string;
  trackingUrl?: string;
  [k: string]: unknown;
}
