/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Method = "CASH" | "PO" | "CREDIT_CARD" | "ON_ACCOUNT";
export type Provider = "FedEx" | "UPS" | "USPS" | "Other";
export type Status = "CREATED";

export interface Order {
  billingAddress: Address;
  comments?: string;
  currencyCode?: string;
  customerIdentifiers?: MapStringObject;
  discounts?: Discount[];
  email?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  /**
   * @minItems 1
   */
  lineItems: [LineItem, ...LineItem[]];
  orderDate?: string;
  /**
   * Globally unique orderNumber.  Usually a combination of sales channel and order number
   */
  orderNumber: string;
  payments?: Payment[];
  salesChannel: string;
  shippingAddress?: Address;
  shippingAmount: number;
  shippingInfo?: ShippingInfo;
  status?: Status;
  subtotal: number;
  taxAmount: number;
  total: number;
  [k: string]: unknown;
}
export interface Address {
  city: string;
  company?: string;
  country?: string;
  firstName?: string;
  identifiers?: MapStringObject;
  lastName?: string;
  phone?: string;
  postal?: string;
  region?: string;
  streets: string[];
  [k: string]: unknown;
}
export interface MapStringObject {
  [k: string]: unknown;
}
export interface Discount {
  amount?: number;
  code?: string;
  description?: string;
  identifiers?: MapStringObject;
  [k: string]: unknown;
}
export interface LineItem {
  children?: LineItem[];
  discountAmount?: number;
  identifiers?: MapStringObject;
  imageUrls?: string[];
  name: string;
  productIdentifiers?: MapStringObject;
  quantity: number;
  sku: string;
  subtotal: number;
  taxAmount: number;
  total: number;
  weightInPounds: number;
  [k: string]: unknown;
}
export interface Payment {
  amount?: number;
  billToName?: string;
  identifiers?: MapStringObject;
  method: Method;
  paymentDate?: string;
  poNumber?: string;
  status?: string;
  [k: string]: unknown;
}
export interface ShippingInfo {
  accountNumber?: string;
  accountType?: string;
  isBlindShipping: boolean;
  method?: string;
  provider: Provider;
  weightInPounds?: number;
  [k: string]: unknown;
}
