/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Product {
  badges?: ProductBadge[];
  brand: string;
  browsable: boolean;
  content?: ProductContent;
  createdAt?: string;
  customization?: ProductCustomization;
  identifiers?: MapStringObject;
  media?: ProductMedia[];
  name: string;
  primaryCategory?: CategoryReference;
  purchaseOptions?: PurchaseOptions;
  searchable: boolean;
  sku: string;
  status?: string;
  taxonomy: Taxonomy;
  upc?: string;
  updatedAt?: string;
  url: string;
  [k: string]: unknown;
}
export interface ProductBadge {
  id?: number;
  imageUrl?: string;
  label?: string;
  [k: string]: unknown;
}
export interface ProductContent {
  longDescription?: string;
  metaDescription?: string;
  metaKeywords?: string;
  metaTitle?: string;
  seoDescription?: string;
  shortDescription?: string;
  [k: string]: unknown;
}
export interface ProductCustomization {
  designRequired: boolean;
  prebuiltConfigurationId?: string;
  prebuiltCustomizable: boolean;
  prebuiltDesign: boolean;
  [k: string]: unknown;
}
export interface MapStringObject {
  [k: string]: unknown;
}
export interface ProductMedia {
  altText?: string;
  mediaType: string;
  tags?: string[];
  url: string;
  [k: string]: unknown;
}
export interface CategoryReference {
  id: number;
  label: string;
  url: string;
  [k: string]: unknown;
}
export interface PurchaseOptions {
  allowsSample: boolean;
  availability: string;
  basePrice: number;
  customizable: boolean;
  customizeLeadTimeDayRange?: string;
  discountReason?: string;
  inStock: boolean;
  leadTime?: string;
  minCustomizationQty?: number;
  minSaleQty: number;
  onSale?: boolean;
  plainLeadTimeDayRange?: string;
  price: number;
  quantityStepIncrements?: QuantityStepIncrement[];
  salePrice?: number;
  stockQty: number;
  suggestedQuantityDisplays?: number[];
  tierPrices?: TierPrice[];
  toBeDiscontinued: boolean;
  [k: string]: unknown;
}
export interface QuantityStepIncrement {
  requiredStepIncrement: number;
  startingAtQty: number;
  [k: string]: unknown;
}
export interface TierPrice {
  price: number;
  startingAtQty: number;
  [k: string]: unknown;
}
export interface Taxonomy {
  additionalProperties?: MapStringObject;
  master: string;
  primary: string;
  sub: string;
  [k: string]: unknown;
}
