/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Shipment {
  carrier?: string;
  comments?: string;
  currencyCode?: string;
  estimatedDeliveryDate?: string;
  identifiers?: MapStringObject;
  lineItems?: LineItem[];
  orderIdentifiers?: MapStringObject;
  /**
   * Globally unique orderNumber.  Usually a combination of sales channel and order number
   */
  orderNumber: string;
  shipmentDate: string;
  trackingNumber?: string;
  trackingUrl?: string;
  [k: string]: unknown;
}
export interface MapStringObject {
  [k: string]: unknown;
}
export interface LineItem {
  children?: LineItem[];
  discountAmount?: number;
  identifiers?: MapStringObject;
  imageUrls?: string[];
  name: string;
  productIdentifiers?: MapStringObject;
  quantity: number;
  sku: string;
  subtotal: number;
  taxAmount: number;
  total: number;
  weightInPounds: number;
  [k: string]: unknown;
}
